version: '3.8'

services:
  # PostgreSQL service
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: nvt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432" 

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount the nginx.conf file

  # Backend service
  backend:
    image: smarthome_backend:latest  # Use the image you built earlier
    container_name: backend_container
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=nvt;Username=postgres;Password=admin"
    ports:
      - "5090:80"  # Map host port 5000 to container port 80
    depends_on:
      - postgres