// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHome.Data;

#nullable disable

namespace SmartHome.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231115174251_remove_state_field")]
    partial class remove_state_field
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.Data.Entities.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("038bd5ae-5f4e-474f-be06-efe33b006f2c"),
                            CountryId = new Guid("a487b860-868e-4375-ac13-0331b0625717"),
                            Name = "New York"
                        },
                        new
                        {
                            Id = new Guid("b0ef0e10-aba9-45c0-9ef1-da085e7f0a45"),
                            CountryId = new Guid("a487b860-868e-4375-ac13-0331b0625717"),
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = new Guid("224bba57-dd9e-4dc6-9377-7a1909d08121"),
                            CountryId = new Guid("a487b860-868e-4375-ac13-0331b0625717"),
                            Name = "Chicago"
                        },
                        new
                        {
                            Id = new Guid("c2ff4c50-d031-4e3f-ad18-8f9a2e1492d9"),
                            CountryId = new Guid("c7b85521-7752-4e18-a15d-382c1f6ef0e3"),
                            Name = "London"
                        },
                        new
                        {
                            Id = new Guid("f4096292-ca86-4168-8d0d-bc73a42ca383"),
                            CountryId = new Guid("55e35db5-31f5-4184-b8ae-ec9b2f95283b"),
                            Name = "Paris"
                        },
                        new
                        {
                            Id = new Guid("224d50f9-17a5-4e98-b755-0267352c346e"),
                            CountryId = new Guid("69717bd8-d87f-4b73-a0cd-066e5f3736cf"),
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = new Guid("f5c8900b-29d3-4761-9c12-7ec7d025475f"),
                            CountryId = new Guid("69dc3b7c-672a-485f-99dd-1665973ec4b0"),
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = new Guid("2b9248f0-e302-4c7d-9b5c-9ed7de0b0e50"),
                            CountryId = new Guid("61b345e2-9cf6-4f86-b4ed-c9b3c2a650df"),
                            Name = "Beijing"
                        },
                        new
                        {
                            Id = new Guid("3a3857b3-56ef-45ab-b527-be03c4f63463"),
                            CountryId = new Guid("a538f002-7836-4fff-ab81-4571c9082adf"),
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = new Guid("9eb6c78a-ab27-46f3-9412-bb6dbb07dc8d"),
                            CountryId = new Guid("4cad111c-9b24-4660-a87e-8cb369e37692"),
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = new Guid("7b5d464b-14cd-4c2a-9e9c-93517e9e756f"),
                            CountryId = new Guid("4692cd79-1790-482a-9063-c7ba170f50b6"),
                            Name = "Mumbai"
                        },
                        new
                        {
                            Id = new Guid("8849cc57-5f7a-4bea-84eb-fd8fa54b4a12"),
                            CountryId = new Guid("f577d21c-b996-4aca-9bf4-df146bf54b7d"),
                            Name = "Cape Town"
                        },
                        new
                        {
                            Id = new Guid("b94ee992-b268-4d5f-a4cc-38d7023410f7"),
                            CountryId = new Guid("a1ff6be2-7ba6-41ea-8fff-a49a4e5ea918"),
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("f734135e-8e6e-4a00-ab10-1b3491ecec28"),
                            CountryId = new Guid("0d898d61-c525-43d4-8cd5-436d657e23d6"),
                            Name = "Moscow"
                        },
                        new
                        {
                            Id = new Guid("cdf75c24-76ba-4464-baf7-0c27bf4a1cf6"),
                            CountryId = new Guid("fd19e97f-6fe5-4c71-b07a-24ecb662e091"),
                            Name = "Dubai"
                        },
                        new
                        {
                            Id = new Guid("b3157d30-8cf3-400b-a6b8-e69617517cdf"),
                            CountryId = new Guid("9f14667f-f967-46db-adc6-53b23ccf13b9"),
                            Name = "Stockholm"
                        },
                        new
                        {
                            Id = new Guid("3921bf84-2687-4fc9-b327-ae58497fc1bf"),
                            CountryId = new Guid("9f516054-e2d4-4274-8dcf-4e9bd747c098"),
                            Name = "Seoul"
                        },
                        new
                        {
                            Id = new Guid("e6eb7c6e-d924-43e5-8920-47ee43903503"),
                            CountryId = new Guid("a7245aba-9a18-4539-82a8-ed212377d8c3"),
                            Name = "Mexico City"
                        },
                        new
                        {
                            Id = new Guid("0c17fd42-ba6c-4946-b84f-c9a57ee18fd5"),
                            CountryId = new Guid("7e8b12b3-3cdc-489f-b276-7dc5605f169f"),
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = new Guid("9bf5dac3-ebc1-4404-a0a7-ee9d0eb16681"),
                            CountryId = new Guid("8636eef2-c829-4219-8fa2-5cf95e82f432"),
                            Name = "Oslo"
                        },
                        new
                        {
                            Id = new Guid("47600cc1-f971-4d4a-af86-2cff072eee43"),
                            CountryId = new Guid("e9c734e6-6695-4f90-8898-a4471c0e4470"),
                            Name = "Hanoi"
                        },
                        new
                        {
                            Id = new Guid("da2b7027-ef57-4091-9b7a-60397a02fcd8"),
                            CountryId = new Guid("24abc113-c34b-42c9-9a6d-a23e299681e3"),
                            Name = "Bangkok"
                        },
                        new
                        {
                            Id = new Guid("8fc14292-5e4d-42b0-8791-e55855023798"),
                            CountryId = new Guid("e5c66940-6e2b-4dd5-9a41-180f9bede4d4"),
                            Name = "Istanbul"
                        },
                        new
                        {
                            Id = new Guid("18fe8afd-85b2-4c03-9580-a229eb9ca9d1"),
                            CountryId = new Guid("8bcd6da6-779c-47f5-b962-295d4526a180"),
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = new Guid("62750f6c-d369-412a-9b61-b2396790cdc4"),
                            CountryId = new Guid("e4df2293-737e-415a-ae20-d5b53e6589ce"),
                            Name = "Rome"
                        },
                        new
                        {
                            Id = new Guid("56c02b16-fce1-427e-a46d-fea9eaccc0c3"),
                            CountryId = new Guid("0d61592e-651d-46d1-9296-908d08293212"),
                            Name = "Cairo"
                        },
                        new
                        {
                            Id = new Guid("df11d3df-bd31-42e8-b0a6-5d0d53ba7084"),
                            CountryId = new Guid("a0d7e642-4556-456a-a645-df2b44722908"),
                            Name = "Lagos"
                        },
                        new
                        {
                            Id = new Guid("83f2cc6a-bef2-4046-8250-8b9639fafb2b"),
                            CountryId = new Guid("8ebda805-936f-4155-b585-a3460c9ddbe9"),
                            Name = "Auckland"
                        },
                        new
                        {
                            Id = new Guid("f247acb5-dbb2-4712-9e54-c52e3d50c072"),
                            CountryId = new Guid("8a614192-9f1c-47cf-88ec-57bab38b7152"),
                            Name = "Nairobi"
                        },
                        new
                        {
                            Id = new Guid("4bbd88f5-a474-4bc9-bc16-9b6bde86338b"),
                            CountryId = new Guid("899ab8ff-d3a5-4967-ba6c-afd33b02d139"),
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = new Guid("0856468f-ab04-4753-97a8-716d2bd6d05f"),
                            CountryId = new Guid("51cc5b23-f4a7-4fdc-8773-18455a391bb1"),
                            Name = "Athens"
                        },
                        new
                        {
                            Id = new Guid("18339fac-03fd-4a2b-9be7-e7acdc1f2808"),
                            CountryId = new Guid("bdca7b68-6b3b-468c-a512-809e19b5157b"),
                            Name = "Dublin"
                        },
                        new
                        {
                            Id = new Guid("ec24bd38-8616-473c-9374-d37cd205e3de"),
                            CountryId = new Guid("e9a53832-e676-4e7c-b3ca-f3ea075ffb51"),
                            Name = "Zurich"
                        },
                        new
                        {
                            Id = new Guid("713a20a9-15c5-4474-88f4-fb8e13e32401"),
                            CountryId = new Guid("d8909638-9869-4772-b4f7-cb6022dee271"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("b952a029-2553-4694-86e4-b9198bda6e2a"),
                            CountryId = new Guid("e0d2a23b-301c-4b28-bcc6-c222055a2210"),
                            Name = "Vienna"
                        },
                        new
                        {
                            Id = new Guid("91b7106f-114e-437f-938a-954a770f042b"),
                            CountryId = new Guid("61b345e2-9cf6-4f86-b4ed-c9b3c2a650df"),
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = new Guid("3050e751-9cc4-481b-8f49-0223f75d3047"),
                            CountryId = new Guid("c517c32c-554a-47c4-a70d-e36aa98c1c9c"),
                            Name = "Copenhagen"
                        },
                        new
                        {
                            Id = new Guid("4366aee7-32b4-41d2-8560-5ac069229b40"),
                            CountryId = new Guid("ecd62d25-939c-483c-b234-942f26b3770c"),
                            Name = "Lisbon"
                        },
                        new
                        {
                            Id = new Guid("b7f69cca-6b7f-45bd-ba49-36fe2259217e"),
                            CountryId = new Guid("6a43676b-40ac-496b-9081-9625a78dade6"),
                            Name = "Warsaw"
                        },
                        new
                        {
                            Id = new Guid("deea4bb9-e00f-490c-92d5-c421b0ef321a"),
                            CountryId = new Guid("afb3148f-dd36-4cad-b92e-5bc83306f191"),
                            Name = "Prague"
                        },
                        new
                        {
                            Id = new Guid("e90ddf01-9be4-4d34-84c1-1ab6625f9e9f"),
                            CountryId = new Guid("5d84c5c2-7bd5-444f-a274-0e9c05de7d3e"),
                            Name = "Budapest"
                        },
                        new
                        {
                            Id = new Guid("d3da3474-6a39-4676-b6de-703fd4026ca6"),
                            CountryId = new Guid("9a4a487d-ef7b-42c6-8a51-45518c9808fd"),
                            Name = "Brussels"
                        },
                        new
                        {
                            Id = new Guid("243da2bc-cef5-40ad-9630-51bb0efb5396"),
                            CountryId = new Guid("4732345b-8f5f-44f1-a5bd-64e2fbdffd83"),
                            Name = "Helsinki"
                        });
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CountryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a487b860-868e-4375-ac13-0331b0625717"),
                            Name = "USA"
                        },
                        new
                        {
                            Id = new Guid("c7b85521-7752-4e18-a15d-382c1f6ef0e3"),
                            Name = "UK"
                        },
                        new
                        {
                            Id = new Guid("55e35db5-31f5-4184-b8ae-ec9b2f95283b"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("69717bd8-d87f-4b73-a0cd-066e5f3736cf"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("69dc3b7c-672a-485f-99dd-1665973ec4b0"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("61b345e2-9cf6-4f86-b4ed-c9b3c2a650df"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("a538f002-7836-4fff-ab81-4571c9082adf"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("4cad111c-9b24-4660-a87e-8cb369e37692"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("4692cd79-1790-482a-9063-c7ba170f50b6"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("f577d21c-b996-4aca-9bf4-df146bf54b7d"),
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("a1ff6be2-7ba6-41ea-8fff-a49a4e5ea918"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("0d898d61-c525-43d4-8cd5-436d657e23d6"),
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("fd19e97f-6fe5-4c71-b07a-24ecb662e091"),
                            Name = "UAE"
                        },
                        new
                        {
                            Id = new Guid("9f14667f-f967-46db-adc6-53b23ccf13b9"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("9f516054-e2d4-4274-8dcf-4e9bd747c098"),
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("a7245aba-9a18-4539-82a8-ed212377d8c3"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("7e8b12b3-3cdc-489f-b276-7dc5605f169f"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("8636eef2-c829-4219-8fa2-5cf95e82f432"),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("e9c734e6-6695-4f90-8898-a4471c0e4470"),
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("24abc113-c34b-42c9-9a6d-a23e299681e3"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("e5c66940-6e2b-4dd5-9a41-180f9bede4d4"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("8bcd6da6-779c-47f5-b962-295d4526a180"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("e4df2293-737e-415a-ae20-d5b53e6589ce"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("0d61592e-651d-46d1-9296-908d08293212"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("a0d7e642-4556-456a-a645-df2b44722908"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("8ebda805-936f-4155-b585-a3460c9ddbe9"),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("8a614192-9f1c-47cf-88ec-57bab38b7152"),
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("899ab8ff-d3a5-4967-ba6c-afd33b02d139"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("51cc5b23-f4a7-4fdc-8773-18455a391bb1"),
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("bdca7b68-6b3b-468c-a512-809e19b5157b"),
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("e9a53832-e676-4e7c-b3ca-f3ea075ffb51"),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("d8909638-9869-4772-b4f7-cb6022dee271"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("e0d2a23b-301c-4b28-bcc6-c222055a2210"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("c517c32c-554a-47c4-a70d-e36aa98c1c9c"),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("ecd62d25-939c-483c-b234-942f26b3770c"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("6a43676b-40ac-496b-9081-9625a78dade6"),
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("afb3148f-dd36-4cad-b92e-5bc83306f191"),
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("5d84c5c2-7bd5-444f-a274-0e9c05de7d3e"),
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("9a4a487d-ef7b-42c6-8a51-45518c9808fd"),
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("4732345b-8f5f-44f1-a5bd-64e2fbdffd83"),
                            Name = "Finland"
                        });
                });

            modelBuilder.Entity("SmartHome.Data.Entities.PropertyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AreaSquareMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CityEntity", b =>
                {
                    b.HasOne("SmartHome.Data.Entities.CountryEntity", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.PropertyEntity", b =>
                {
                    b.HasOne("SmartHome.Data.Entities.CityEntity", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CityEntity", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CountryEntity", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
