// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHome.Data;

#nullable disable

namespace SmartHome.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231116170946_activationToken")]
    partial class activationToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.Data.Entities.ActivationTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("expires")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ActivationTokens");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1f37512-4c71-489f-b5ce-317c0c2f9ead"),
                            CountryId = new Guid("15a7a869-cbe0-425d-86c2-509ec15b3f99"),
                            Name = "New York"
                        },
                        new
                        {
                            Id = new Guid("78beaddd-d280-4113-9fab-2d2bac5d341f"),
                            CountryId = new Guid("15a7a869-cbe0-425d-86c2-509ec15b3f99"),
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = new Guid("eaccd883-8bef-4952-a2ed-2a8e8963173e"),
                            CountryId = new Guid("15a7a869-cbe0-425d-86c2-509ec15b3f99"),
                            Name = "Chicago"
                        },
                        new
                        {
                            Id = new Guid("7af3b08d-d5c1-4b2e-8817-107077258a3d"),
                            CountryId = new Guid("f042d6ad-f618-4efc-9d4e-994a696c4b2b"),
                            Name = "London"
                        },
                        new
                        {
                            Id = new Guid("bd1bd405-6a23-4f05-b599-6d15e4a7bf7d"),
                            CountryId = new Guid("e3028d61-ec8f-45fa-8171-bf1269adb444"),
                            Name = "Paris"
                        },
                        new
                        {
                            Id = new Guid("920f6caa-910d-427d-a40c-1c8d8c34b3d0"),
                            CountryId = new Guid("3de53b34-e76e-4c94-abd2-9a7a40a05862"),
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = new Guid("dfd3a3b4-7d61-45fa-bf29-e325a33cb48d"),
                            CountryId = new Guid("04876628-e480-4652-9243-ec274fd057f5"),
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = new Guid("61d1485b-b145-4ab1-b0e1-763e86fedc3b"),
                            CountryId = new Guid("5b607638-0652-4b31-922e-08f2b366acb4"),
                            Name = "Beijing"
                        },
                        new
                        {
                            Id = new Guid("c5aec408-5cc7-4ed1-b929-2c06adec7756"),
                            CountryId = new Guid("d95214be-baa2-4f5b-bcbb-4d73df94e816"),
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = new Guid("faf87d52-2ec3-407b-8fc6-167ce27a8b53"),
                            CountryId = new Guid("d621486d-38c8-4b4d-8f78-51af174b2be9"),
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = new Guid("891354f2-b88a-4529-88d1-7c65d27ed9f4"),
                            CountryId = new Guid("d4a66b05-de3c-4130-a451-60c892bcd161"),
                            Name = "Mumbai"
                        },
                        new
                        {
                            Id = new Guid("16ff56af-53d3-4b4f-a054-d5e922484131"),
                            CountryId = new Guid("b7c4a4b5-62a6-49b8-9778-46d85e4b1e45"),
                            Name = "Cape Town"
                        },
                        new
                        {
                            Id = new Guid("11d6c4af-6e9f-4e3c-a065-38e8459d2ec2"),
                            CountryId = new Guid("2132ad7f-c64c-4a19-a941-eaba3b438e3f"),
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("ea081413-4717-4c9f-b8d2-6e07b4ef1b36"),
                            CountryId = new Guid("49812ba2-bb96-40df-9453-39448ece5fe5"),
                            Name = "Moscow"
                        },
                        new
                        {
                            Id = new Guid("092a73a0-fb9b-4d6f-ab75-b5edba898fe1"),
                            CountryId = new Guid("0b226749-672e-4b27-b0a8-840dcf0310b5"),
                            Name = "Dubai"
                        },
                        new
                        {
                            Id = new Guid("0b0aeb11-311f-4b8f-9297-aa4172a0e858"),
                            CountryId = new Guid("7e40d244-e2aa-4f57-9fcb-70a4b530673f"),
                            Name = "Stockholm"
                        },
                        new
                        {
                            Id = new Guid("669bb2b1-72ba-40ca-b7c8-fe1f64ffeff8"),
                            CountryId = new Guid("76c3cf89-d800-4088-bda4-e84e7b2fea48"),
                            Name = "Seoul"
                        },
                        new
                        {
                            Id = new Guid("7f0b2cf2-6ba6-4403-82ac-676543cf727c"),
                            CountryId = new Guid("e27b2ca2-b1e9-4ec4-89ac-0d6dd379adb0"),
                            Name = "Mexico City"
                        },
                        new
                        {
                            Id = new Guid("ff387770-6dcd-4e3c-92e4-1cbee0d405a2"),
                            CountryId = new Guid("c6ecaee9-2fc2-4cdb-9f48-18dcc871f85b"),
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = new Guid("d337beba-a01c-4d8d-ad0c-b522bd98c3c6"),
                            CountryId = new Guid("c970d1fb-2ece-4c02-bcb4-4454e0d2789e"),
                            Name = "Oslo"
                        },
                        new
                        {
                            Id = new Guid("f28a5634-c0d1-45f1-aad5-8d3616a05efd"),
                            CountryId = new Guid("b6839cf4-d46f-4e05-a798-22e1a561ff17"),
                            Name = "Hanoi"
                        },
                        new
                        {
                            Id = new Guid("8cbf953c-6474-4929-9536-a907dc41e2d3"),
                            CountryId = new Guid("df46da8a-95be-4cab-99df-5bb909a7dcc2"),
                            Name = "Bangkok"
                        },
                        new
                        {
                            Id = new Guid("0659eb91-c4a6-464f-bc38-18d154a6a15b"),
                            CountryId = new Guid("6ca39e54-ac1a-4e1a-8f0d-9d567d5f4113"),
                            Name = "Istanbul"
                        },
                        new
                        {
                            Id = new Guid("1141f023-0da2-4a68-99cf-eae2df62b82b"),
                            CountryId = new Guid("6ae12890-b72f-4df8-a3db-b3e458126cf2"),
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = new Guid("4a5920b6-067c-457a-b0b1-fab0c6047ad8"),
                            CountryId = new Guid("96622d57-6e98-48b5-b66b-e622c46bc95a"),
                            Name = "Rome"
                        },
                        new
                        {
                            Id = new Guid("e39af11f-4066-40ef-805d-de3d81a0cee8"),
                            CountryId = new Guid("40f6f970-98ec-47e1-86ec-605abf2e9197"),
                            Name = "Cairo"
                        },
                        new
                        {
                            Id = new Guid("66398b0d-52b8-4158-b35c-928f941340a9"),
                            CountryId = new Guid("01f76d47-dac1-49db-8cc6-aee0de026ee8"),
                            Name = "Lagos"
                        },
                        new
                        {
                            Id = new Guid("244adc99-22b7-4f2f-9f1a-3abf7bda95ed"),
                            CountryId = new Guid("401b4e1d-d2e1-4bfc-a67f-de8b2ad1885c"),
                            Name = "Auckland"
                        },
                        new
                        {
                            Id = new Guid("f58b0e76-48c5-4735-906f-600220c9bc0a"),
                            CountryId = new Guid("7911dfe3-df80-459b-89e2-dca8c45cd468"),
                            Name = "Nairobi"
                        },
                        new
                        {
                            Id = new Guid("da574b24-c881-4740-9d70-3da30e75d320"),
                            CountryId = new Guid("25945e15-5fee-4265-b4dc-db9783f5490c"),
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = new Guid("ef6c4888-ee7a-4ede-a7f7-ef237155abc3"),
                            CountryId = new Guid("03d4adfc-9236-4997-871e-21a0678bf142"),
                            Name = "Athens"
                        },
                        new
                        {
                            Id = new Guid("1a5dac0a-9a45-404a-9b3b-33e96a55bc86"),
                            CountryId = new Guid("68d5272f-9407-4f93-abea-d050c17756b8"),
                            Name = "Dublin"
                        },
                        new
                        {
                            Id = new Guid("dad89734-bff5-4fee-a2fe-4f63735b905b"),
                            CountryId = new Guid("22e160a4-dc0d-4703-b9f2-2e93b916582b"),
                            Name = "Zurich"
                        },
                        new
                        {
                            Id = new Guid("97f0bc44-ba09-44d5-9d21-101a21a0ed2f"),
                            CountryId = new Guid("957eb859-1d83-4364-8e6e-b75926311053"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("1ba1553c-a83b-4c82-a3f0-1ac81d355c62"),
                            CountryId = new Guid("d99b83e1-530a-4d2e-b9aa-465ac1acb070"),
                            Name = "Vienna"
                        },
                        new
                        {
                            Id = new Guid("def4121f-4faf-49db-a650-005937197df8"),
                            CountryId = new Guid("5b607638-0652-4b31-922e-08f2b366acb4"),
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = new Guid("2a2f6ed1-8d93-47f2-8935-d2fc8c6b0f33"),
                            CountryId = new Guid("f58a3058-6d7b-4858-b0f4-da6c914295d7"),
                            Name = "Copenhagen"
                        },
                        new
                        {
                            Id = new Guid("24c444cd-e20b-44e7-a7cd-c6651fb53b1f"),
                            CountryId = new Guid("d03a8568-79bb-4a3c-96a6-7dbf49646586"),
                            Name = "Lisbon"
                        },
                        new
                        {
                            Id = new Guid("2b461ddd-02ff-4e12-8a73-7a725c1a0222"),
                            CountryId = new Guid("299ece92-1c98-4664-9f3d-eab9a5984696"),
                            Name = "Warsaw"
                        },
                        new
                        {
                            Id = new Guid("5f14de5f-d6f4-4549-b0a1-f08c38f40216"),
                            CountryId = new Guid("5677cc47-5895-4733-9097-755d658c9c7d"),
                            Name = "Prague"
                        },
                        new
                        {
                            Id = new Guid("616430de-c994-4417-b705-552c3a5a3593"),
                            CountryId = new Guid("8ef5184d-987a-4ade-8ad1-a141163a00ed"),
                            Name = "Budapest"
                        },
                        new
                        {
                            Id = new Guid("0c53d859-f73b-4f62-8a76-3311bab77f4f"),
                            CountryId = new Guid("b4c81d1e-99bc-4e9c-96ff-b6d6dc6a0b02"),
                            Name = "Brussels"
                        },
                        new
                        {
                            Id = new Guid("5042e88c-aca9-45d4-a8fe-eb6691f5c13c"),
                            CountryId = new Guid("bd0555fd-11ba-4de2-8cb8-9ac7df9b7280"),
                            Name = "Helsinki"
                        });
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CountryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15a7a869-cbe0-425d-86c2-509ec15b3f99"),
                            Name = "USA"
                        },
                        new
                        {
                            Id = new Guid("f042d6ad-f618-4efc-9d4e-994a696c4b2b"),
                            Name = "UK"
                        },
                        new
                        {
                            Id = new Guid("e3028d61-ec8f-45fa-8171-bf1269adb444"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("3de53b34-e76e-4c94-abd2-9a7a40a05862"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("04876628-e480-4652-9243-ec274fd057f5"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("5b607638-0652-4b31-922e-08f2b366acb4"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("d95214be-baa2-4f5b-bcbb-4d73df94e816"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("d621486d-38c8-4b4d-8f78-51af174b2be9"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("d4a66b05-de3c-4130-a451-60c892bcd161"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("b7c4a4b5-62a6-49b8-9778-46d85e4b1e45"),
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("2132ad7f-c64c-4a19-a941-eaba3b438e3f"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("49812ba2-bb96-40df-9453-39448ece5fe5"),
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("0b226749-672e-4b27-b0a8-840dcf0310b5"),
                            Name = "UAE"
                        },
                        new
                        {
                            Id = new Guid("7e40d244-e2aa-4f57-9fcb-70a4b530673f"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("76c3cf89-d800-4088-bda4-e84e7b2fea48"),
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("e27b2ca2-b1e9-4ec4-89ac-0d6dd379adb0"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("c6ecaee9-2fc2-4cdb-9f48-18dcc871f85b"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("c970d1fb-2ece-4c02-bcb4-4454e0d2789e"),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("b6839cf4-d46f-4e05-a798-22e1a561ff17"),
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("df46da8a-95be-4cab-99df-5bb909a7dcc2"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("6ca39e54-ac1a-4e1a-8f0d-9d567d5f4113"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("6ae12890-b72f-4df8-a3db-b3e458126cf2"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("96622d57-6e98-48b5-b66b-e622c46bc95a"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("40f6f970-98ec-47e1-86ec-605abf2e9197"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("01f76d47-dac1-49db-8cc6-aee0de026ee8"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("401b4e1d-d2e1-4bfc-a67f-de8b2ad1885c"),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("7911dfe3-df80-459b-89e2-dca8c45cd468"),
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("25945e15-5fee-4265-b4dc-db9783f5490c"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("03d4adfc-9236-4997-871e-21a0678bf142"),
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("68d5272f-9407-4f93-abea-d050c17756b8"),
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("22e160a4-dc0d-4703-b9f2-2e93b916582b"),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("957eb859-1d83-4364-8e6e-b75926311053"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("d99b83e1-530a-4d2e-b9aa-465ac1acb070"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("f58a3058-6d7b-4858-b0f4-da6c914295d7"),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("d03a8568-79bb-4a3c-96a6-7dbf49646586"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("299ece92-1c98-4664-9f3d-eab9a5984696"),
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("5677cc47-5895-4733-9097-755d658c9c7d"),
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("8ef5184d-987a-4ade-8ad1-a141163a00ed"),
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("b4c81d1e-99bc-4e9c-96ff-b6d6dc6a0b02"),
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("bd0555fd-11ba-4de2-8cb8-9ac7df9b7280"),
                            Name = "Finland"
                        });
                });

            modelBuilder.Entity("SmartHome.Data.Entities.PropertyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AreaSquareMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CityEntity", b =>
                {
                    b.HasOne("SmartHome.Data.Entities.CountryEntity", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.PropertyEntity", b =>
                {
                    b.HasOne("SmartHome.Data.Entities.CityEntity", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CityEntity", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CountryEntity", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
