// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHome.Data;

#nullable disable

namespace SmartHome.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231115170748_add_cities_countries")]
    partial class add_cities_countries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.Data.Entities.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c85de4ae-6786-4e84-bc4e-40717952bd01"),
                            CountryId = new Guid("ce95ee7c-d4ee-4d10-b520-b397180335c4"),
                            Name = "New York"
                        },
                        new
                        {
                            Id = new Guid("77f5fe75-2f60-4a76-90e2-d445b2529344"),
                            CountryId = new Guid("ce95ee7c-d4ee-4d10-b520-b397180335c4"),
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = new Guid("2385cbec-8697-4964-9b8a-b52f117be4d2"),
                            CountryId = new Guid("ce95ee7c-d4ee-4d10-b520-b397180335c4"),
                            Name = "Chicago"
                        },
                        new
                        {
                            Id = new Guid("e73c37f0-c4ab-4613-9ca5-26eae3400033"),
                            CountryId = new Guid("e4537558-1c23-40e0-a559-df1074d26b45"),
                            Name = "London"
                        },
                        new
                        {
                            Id = new Guid("c9432e20-beb8-4c61-b5c5-0dc1a9d4f406"),
                            CountryId = new Guid("e1bfb08f-5636-44ec-a4db-bcc398d18f46"),
                            Name = "Paris"
                        },
                        new
                        {
                            Id = new Guid("23db35bb-9251-4202-b06e-5420672b74ad"),
                            CountryId = new Guid("f74c5676-6f40-4447-9135-9fc19a7152bb"),
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = new Guid("38215fbc-6ca2-4e10-85e1-d5be6c9af2fb"),
                            CountryId = new Guid("ecba7d9e-9b4f-4610-8096-87f6eb663110"),
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = new Guid("56b03cfb-48bc-44bc-b3d3-815cc5b964db"),
                            CountryId = new Guid("aeb2da0d-5b65-47f3-83a0-12f6764db54f"),
                            Name = "Beijing"
                        },
                        new
                        {
                            Id = new Guid("eb220fbb-5364-40ef-babd-557fc8bfc3f8"),
                            CountryId = new Guid("c7ead1d2-a1f0-4f1c-a6d4-561ecffdab3e"),
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = new Guid("d91146e7-06a7-4cf6-a6e0-ed52acf19e57"),
                            CountryId = new Guid("f801aba6-6ef2-483c-b987-d29bfa0a22b2"),
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = new Guid("f2009493-5511-4163-b8e1-e718236b1bcc"),
                            CountryId = new Guid("06ae197e-f7ec-4c4e-9b33-7423bc09d158"),
                            Name = "Mumbai"
                        },
                        new
                        {
                            Id = new Guid("e1ed0dce-24ad-4cc3-bc40-82e0536f9c4b"),
                            CountryId = new Guid("353316dd-f171-4149-951f-272a234bf910"),
                            Name = "Cape Town"
                        },
                        new
                        {
                            Id = new Guid("6d2e2a48-45e2-4a9e-b0e7-e62918a22faf"),
                            CountryId = new Guid("88547e50-5d34-4ae3-8384-6b671bf338ff"),
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("0ba6f3e8-0407-4dea-b92b-fd782a688a79"),
                            CountryId = new Guid("001d0400-8069-4831-bd8a-e7960c77ca00"),
                            Name = "Moscow"
                        },
                        new
                        {
                            Id = new Guid("ad8e4fb1-f933-4eef-b335-24f38697101a"),
                            CountryId = new Guid("439e4dca-082a-48ac-a600-e4bb29baaf83"),
                            Name = "Dubai"
                        },
                        new
                        {
                            Id = new Guid("5d957a27-5916-4094-9b79-dde9b259e68e"),
                            CountryId = new Guid("4c6f861a-256b-40a3-a39b-030bfaebf0e8"),
                            Name = "Stockholm"
                        },
                        new
                        {
                            Id = new Guid("ab0a8e1f-e4d2-4f20-b776-681333d2e9ae"),
                            CountryId = new Guid("246a520b-beda-4eec-9305-e9504761a0ad"),
                            Name = "Seoul"
                        },
                        new
                        {
                            Id = new Guid("467b1f83-a872-415c-9ecd-2e6d76dbfea5"),
                            CountryId = new Guid("cca165f6-8567-491a-9a04-58a9fd715c10"),
                            Name = "Mexico City"
                        },
                        new
                        {
                            Id = new Guid("88ce900c-432b-4f46-8786-eea2d77b10ba"),
                            CountryId = new Guid("81c593af-2a7f-4589-8862-e0caaadb1c21"),
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = new Guid("bd450c30-ad38-48d9-9654-a947f90dc4a5"),
                            CountryId = new Guid("8e33f77e-ca76-40fb-b386-c10aaccfa4d3"),
                            Name = "Oslo"
                        },
                        new
                        {
                            Id = new Guid("71d48394-f90b-4c9b-8d69-50a0ba3fbd2e"),
                            CountryId = new Guid("6d863dff-235e-4b1c-8310-be6d9564c3c5"),
                            Name = "Hanoi"
                        },
                        new
                        {
                            Id = new Guid("b583d9d6-8274-49de-9f56-1222caed1fcc"),
                            CountryId = new Guid("2d153fbd-86b9-4cbd-a85a-edef793fa065"),
                            Name = "Bangkok"
                        },
                        new
                        {
                            Id = new Guid("a9705c60-c172-4820-b7e8-eb160fd21443"),
                            CountryId = new Guid("73229010-6971-4016-82c0-056de0a0ee5a"),
                            Name = "Istanbul"
                        },
                        new
                        {
                            Id = new Guid("9846bc0f-e3b1-4778-9aa5-33352f9e4215"),
                            CountryId = new Guid("60d49e4e-d733-4dbb-a4e9-ed89ae388fd3"),
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = new Guid("0ceb5e2e-e328-42e6-8733-0febc8a9a869"),
                            CountryId = new Guid("310ae403-e2d9-425b-ae37-11f9e6eba134"),
                            Name = "Rome"
                        },
                        new
                        {
                            Id = new Guid("fa9fd9a2-21b5-448c-abf8-3d00df2b8b74"),
                            CountryId = new Guid("39a1c684-b99e-4fc5-835b-4cfa4e7cb86a"),
                            Name = "Cairo"
                        },
                        new
                        {
                            Id = new Guid("a123633b-a109-47dc-a4c0-0afa18e8be4d"),
                            CountryId = new Guid("a8f8631f-1671-4c1c-a9d6-6d919969e471"),
                            Name = "Lagos"
                        },
                        new
                        {
                            Id = new Guid("b54d6e16-d2c6-4e0a-abc8-5dabc7e6f2f5"),
                            CountryId = new Guid("3fe69907-2c99-4cb3-b5e2-919998a72dcf"),
                            Name = "Auckland"
                        },
                        new
                        {
                            Id = new Guid("bb0f731f-d58e-4bcc-880b-2477a4f37b73"),
                            CountryId = new Guid("c04042c6-c471-4d2c-9617-2916a3c66bdc"),
                            Name = "Nairobi"
                        },
                        new
                        {
                            Id = new Guid("8b07b70a-b51c-405c-9a5e-d2b00de0fbde"),
                            CountryId = new Guid("55ac250e-9ff3-4dd1-8450-b3640517d08d"),
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = new Guid("0b5e7297-0c91-462e-97ba-c979312b1c34"),
                            CountryId = new Guid("0b2c3386-02e3-4147-a756-485ffb6a4b35"),
                            Name = "Athens"
                        },
                        new
                        {
                            Id = new Guid("9c0c80b9-02bf-4fe5-b713-9c50525d64d6"),
                            CountryId = new Guid("5bf24e24-1dc0-480c-ae29-345d828a1ca4"),
                            Name = "Dublin"
                        },
                        new
                        {
                            Id = new Guid("85513312-3315-4536-804f-7ed3f332152d"),
                            CountryId = new Guid("cdd4d44f-8a6f-4136-8d3c-c03905d14f46"),
                            Name = "Zurich"
                        },
                        new
                        {
                            Id = new Guid("3e044031-f4ff-4329-92be-87111328bf5b"),
                            CountryId = new Guid("4a158e35-abd5-4cd6-8255-ee3920bb542b"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("8fde6d88-6914-4b67-b062-aaf79b8aa22f"),
                            CountryId = new Guid("ac48a9dd-df13-49a3-87fa-012c27900b62"),
                            Name = "Vienna"
                        },
                        new
                        {
                            Id = new Guid("bd818fda-668d-47cf-a7c4-7a594f4deb22"),
                            CountryId = new Guid("aeb2da0d-5b65-47f3-83a0-12f6764db54f"),
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = new Guid("068676fd-eb30-4360-9228-671e5f3af640"),
                            CountryId = new Guid("d9bb4c52-7c1d-447b-8b2c-93d454e76491"),
                            Name = "Copenhagen"
                        },
                        new
                        {
                            Id = new Guid("2257b18d-d7f0-451a-992d-7c821a3eb8c8"),
                            CountryId = new Guid("e9298563-8669-4661-900a-348a366e48db"),
                            Name = "Lisbon"
                        },
                        new
                        {
                            Id = new Guid("90fbf35a-de7c-4d55-8f87-cadbdec2af05"),
                            CountryId = new Guid("04f751fd-5041-40d4-a460-8644cff8d689"),
                            Name = "Warsaw"
                        },
                        new
                        {
                            Id = new Guid("e805b847-df83-42db-841d-58553b5e5376"),
                            CountryId = new Guid("ad494b8c-1712-4dae-856e-b298c5594c0e"),
                            Name = "Prague"
                        },
                        new
                        {
                            Id = new Guid("678c7c05-d356-466f-9417-02aaa072e65b"),
                            CountryId = new Guid("6e193476-c988-41a2-8a75-c5b6801d0caf"),
                            Name = "Budapest"
                        },
                        new
                        {
                            Id = new Guid("fd110166-ec59-4b39-a852-5cbace1b2444"),
                            CountryId = new Guid("5fe2e7b2-2a1f-432a-8389-a4649ac221a5"),
                            Name = "Brussels"
                        },
                        new
                        {
                            Id = new Guid("46c42b20-da6a-46f8-86f2-c6e780b59b74"),
                            CountryId = new Guid("95539198-93cd-4555-a3b9-65c28486cc5f"),
                            Name = "Helsinki"
                        });
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CountryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce95ee7c-d4ee-4d10-b520-b397180335c4"),
                            Name = "USA"
                        },
                        new
                        {
                            Id = new Guid("e4537558-1c23-40e0-a559-df1074d26b45"),
                            Name = "UK"
                        },
                        new
                        {
                            Id = new Guid("e1bfb08f-5636-44ec-a4db-bcc398d18f46"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("f74c5676-6f40-4447-9135-9fc19a7152bb"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("ecba7d9e-9b4f-4610-8096-87f6eb663110"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("aeb2da0d-5b65-47f3-83a0-12f6764db54f"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("c7ead1d2-a1f0-4f1c-a6d4-561ecffdab3e"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("f801aba6-6ef2-483c-b987-d29bfa0a22b2"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("06ae197e-f7ec-4c4e-9b33-7423bc09d158"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("353316dd-f171-4149-951f-272a234bf910"),
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("88547e50-5d34-4ae3-8384-6b671bf338ff"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("001d0400-8069-4831-bd8a-e7960c77ca00"),
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("439e4dca-082a-48ac-a600-e4bb29baaf83"),
                            Name = "UAE"
                        },
                        new
                        {
                            Id = new Guid("4c6f861a-256b-40a3-a39b-030bfaebf0e8"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("246a520b-beda-4eec-9305-e9504761a0ad"),
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("cca165f6-8567-491a-9a04-58a9fd715c10"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("81c593af-2a7f-4589-8862-e0caaadb1c21"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("8e33f77e-ca76-40fb-b386-c10aaccfa4d3"),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("6d863dff-235e-4b1c-8310-be6d9564c3c5"),
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("2d153fbd-86b9-4cbd-a85a-edef793fa065"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("73229010-6971-4016-82c0-056de0a0ee5a"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("60d49e4e-d733-4dbb-a4e9-ed89ae388fd3"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("310ae403-e2d9-425b-ae37-11f9e6eba134"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("39a1c684-b99e-4fc5-835b-4cfa4e7cb86a"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("a8f8631f-1671-4c1c-a9d6-6d919969e471"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("3fe69907-2c99-4cb3-b5e2-919998a72dcf"),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("c04042c6-c471-4d2c-9617-2916a3c66bdc"),
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("55ac250e-9ff3-4dd1-8450-b3640517d08d"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("0b2c3386-02e3-4147-a756-485ffb6a4b35"),
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("5bf24e24-1dc0-480c-ae29-345d828a1ca4"),
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("cdd4d44f-8a6f-4136-8d3c-c03905d14f46"),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("4a158e35-abd5-4cd6-8255-ee3920bb542b"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("ac48a9dd-df13-49a3-87fa-012c27900b62"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("d9bb4c52-7c1d-447b-8b2c-93d454e76491"),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("e9298563-8669-4661-900a-348a366e48db"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("04f751fd-5041-40d4-a460-8644cff8d689"),
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("ad494b8c-1712-4dae-856e-b298c5594c0e"),
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("6e193476-c988-41a2-8a75-c5b6801d0caf"),
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("5fe2e7b2-2a1f-432a-8389-a4649ac221a5"),
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("95539198-93cd-4555-a3b9-65c28486cc5f"),
                            Name = "Finland"
                        });
                });

            modelBuilder.Entity("SmartHome.Data.Entities.PropertyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AreaSquareMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CityEntity", b =>
                {
                    b.HasOne("SmartHome.Data.Entities.CountryEntity", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.PropertyEntity", b =>
                {
                    b.HasOne("SmartHome.Data.Entities.CityEntity", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CityEntity", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("SmartHome.Data.Entities.CountryEntity", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
