version: '3'
services:

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: nvt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_container
    ports:
      - "8883:1883"
    volumes:
      - ./mosqutto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  influx:
    image: influxdb:latest
    container_name: influx_container
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_USER=myuser
      - INFLUXDB_USER_PASSWORD=mypassword
      - INFLUXDB_ORG=organization
      - INFLUXDB_BUCKET=bucket
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
 
   
    